"""initial terminology schema

Revision ID: 9d727d45a64d
Revises: 
Create Date: 2026-08-14 12:23:40.700550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '9d727d45a64d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('ontology_releases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ontology', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ontology_releases_ontology'), 'ontology_releases', ['ontology'], unique=False)
    op.create_table('concepts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ontology', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('preferred_term', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['ontology_releases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concepts_code'), 'concepts', ['code'], unique=False)
    op.create_index(op.f('ix_concepts_ontology'), 'concepts', ['ontology'], unique=False)
    op.create_table('ontology_embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('ontology', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('embedding_version', sa.String(), nullable=True),
    sa.Column('source_text_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ontology_embeddings_concept_id'), 'ontology_embeddings', ['concept_id'], unique=False)
    op.create_index(op.f('ix_ontology_embeddings_ontology'), 'ontology_embeddings', ['ontology'], unique=False)
    op.create_table('relationships',
    sa.Column('source_concept_id', sa.Uuid(), nullable=False),
    sa.Column('target_concept_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('ontology', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['target_concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('source_concept_id', 'target_concept_id', 'relationship_type')
    )
    op.create_table('terms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('concept_id', sa.Uuid(), nullable=False),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('normalized_term', sa.Text(), nullable=False),
    sa.Column('term_type', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terms_concept_id'), 'terms', ['concept_id'], unique=False)
    op.create_index(op.f('ix_terms_normalized_term'), 'terms', ['normalized_term'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_terms_normalized_term'), table_name='terms')
    op.drop_index(op.f('ix_terms_concept_id'), table_name='terms')
    op.drop_table('terms')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_ontology_embeddings_ontology'), table_name='ontology_embeddings')
    op.drop_index(op.f('ix_ontology_embeddings_concept_id'), table_name='ontology_embeddings')
    op.drop_table('ontology_embeddings')
    op.drop_index(op.f('ix_concepts_ontology'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_code'), table_name='concepts')
    op.drop_table('concepts')
    op.drop_index(op.f('ix_ontology_releases_ontology'), table_name='ontology_releases')
    op.drop_table('ontology_releases')
    # ### end Alembic commands ###
